name: Sync To Gitee

on: [ push, delete, create ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.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 }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: https://github.com/kurisaW/kurisaW_docs.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: https://gitee.com/kurisaW/kurisaW_docs.git
